### ISSUE TITLE
New 0.11.0 Isn't compatible with older Matplotlib that runs on Python2.7

### ISSUE THREAD

**Issue by eggoynes** [matplotlib/cycler#77]
When running version 0.11.0 with Matplotlib 2.x.x on Python 2.7 get following error because of the f string usage. 
https://pypi.org/project/cycler/0.11.0/

Basically just have to make sure if installing Matplotlib 2.x.x on Python 2.7 to force install 0.10.0

```
pip install cycler==0.10.0
```

```
Traceback (most recent call last):
 File "/usr/local/bin/pynmonanalyzer", line 26, in <module>
  import pyNmonPlotter
 File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pynmonanalyzer/pyNmonPlotter.py", line 24, in <module>
  import matplotlib as mpl
 File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 124, in <module>
  from matplotlib.rcsetup import (defaultParams,
 File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/matplotlib/rcsetup.py", line 37, in <module>
  from cycler import Cycler, cycler as ccycler
 File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/cycler.py", line 260
  f"not {len(self)} and {len(other)}")
  ^
SyntaxError: invalid syntax
```

**Comment by QuLogic** [comment]
Cycler 0.11.0 [requires Python 3.6](https://github.com/matplotlib/cycler/blob/v0.11.0/setup.py#L12); how did you manage to install it?

**Comment by QuLogic** [comment]
Going to close for lack of response, and that this installation is unsupported.
